baseURL = "https://refi2305.github.io/test-grafian-hugo/"
languageCode = "en-us"
title = "Grafian Software Crafter"
theme = "ananke"

contentDir = "content"
layoutDir = "layouts"
publishDir = "docs"
buildDraft = false

[taxonomies]
 category = "categories"
 tag = "tags"

[params]
 subtitle = "Hugo is Cool"
 author = "Refi R"
